apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 2
  selector:
    matchLabels:
      run: client
  template:
    metadata:
      labels:
        run: client
    spec:
      containers:
        - name: client
          image: baohuynh0188/client
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '2Gi'
              cpu: 500m
            requests:
              memory: '1Gi'
              cpu: 200m
